### ISSUE TITLE
Unused option use_tls 

### ISSUE THREAD

**Issue by Skywalker-11** [FreeDSx/LDAP#19]
In https://github.com/FreeDSx/LDAP/blob/master/src/FreeDSx/Ldap/LdapClient.php and https://github.com/FreeDSx/LDAP/blob/master/tests/spec/FreeDSx/Ldap/LdapClientSpec.php the option `use_tls` is defined in the options but never used. 

This can cause confusion as app developers may try to use this instead of `use_ssl` as TLS1.0, TLS1.1 are associated with higher security that SSL2 or SSL3 and results in a setup where passwords and data is transmitted in plain text

**Comment by ChadSikorra** [comment]
Yeah, that should be removed. My original thought was to allow that option to be toggled and the client would automatically initiate a startTls when creating the initial connection. However, I never ended up implementing or documenting that option:

https://github.com/FreeDSx/LDAP/blob/master/docs/Client/Configuration.md

So yeah, at this point it should be removed altogether to avoid confusion and general clean-up.

**Comment by ChadSikorra** [comment]
Also, just to clarify, the `use_ssl` option is completely different from issuing a `startTls()` with the LdapClient. That doesn't mean that the connection will then use SSL 2.0 / SSL 3.0, but rather refers to what is commonly called LDAPS. Which is initiating LDAP over an encrypted tunnel. In most cases this is done over port 636. 

Whether TLS 1.2 / TLS 1.1 / TLS 1.0 is used is defined in the Socket library (Specifically, here: https://github.com/FreeDSx/Socket/blob/master/src/FreeDSx/Socket/Socket.php#L86). I have not exposed the ssl_crypto_type option from the socket class to be defined via how it's used in this library.

**Comment by ChadSikorra** [comment]
Removed in https://github.com/FreeDSx/LDAP/commit/6056f205949b0f7e188ae18fb2d0f5dad8b79da9. Please only use configuration options documented in the docs.
