### ISSUE TITLE
Thanx and a small suggestion...

### ISSUE THREAD

**Issue by Stephanowicz** [FreeDSx/LDAP#22]
Hi,

first of all: thank You for this! It's exactly what I've been looking for - I've just a flat phonebook and I needed a SIMPLE backend for my IP-Phones for LDAP-queries.

Suggestion: as I'm not familiar with composer it took me almost half a day to figure out how to get it running... :D

So I think it would be helpful if You could add an extra general chapter in the readme just for the installation.
Maybe smth like this:

```
git clone https://github.com/FreeDSx/LDAP.git
cd LDAP/
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php composer-setup.php --filename=composer
./composer i
./composer dump-autoload

php LdapServer.php
```

Thank You & cheers,

Stephan

**Comment by ChadSikorra** [comment]
Hi there Stephan. I'm glad you found the library useful! I have added a link in the "Getting Started" section of the readme that goes to the home page of composer. I think that's all I will do for this one though. Composer is pretty much the de facto standard for package management in PHP, so I don't think it's worth diving too deep into how to use it specifically for this project.

But I'm glad you got it figured out! And good luck with the project (:
