### ISSUE TITLE
UTF-8 supporting

### ISSUE THREAD

**Issue by azovsky** [FreeDSx/LDAP#26]
In my custom LDAP server I build and return a search result similar to the documentation:

```php
$entries = new Entries();
...
$entries->add(
	Entry::fromArray('uid=...', [
		'cn' => $row['name'] ?: 'Name',
		'sn' => $row['name_family'] ?: 'Family name',
		'uid' => $row['uid'],
		...
	])
);
```
and everything works great! 

Only issues if a "name" field or other value have "non-standard" characters, e.g. for `Peña` name. In this case I see in the response from my server name string as 
`cn:: QXJnZW5pcyBQZcOxYQ==` 
instead 
`cn: Peña`.

How I can fix this? I reviewed all the code and looks like it is "converted" in some "socket level"... I'm not sure.

Someone can tell me what the problem is? 
Thank you!

**Comment by ChadSikorra** [comment]
If you are searching the server using ldap_search from the command line, that tool will automatically convert strings to base64 encoding when it contains multibyte characters. I think that is what is happening anyway.

**Comment by azovsky** [comment]
You're right! I changed the database encoding to `utf8_general_ci` and all good now.
But the command line, yes, I still see "encoded" strings.
Thanks for quick answers!

**Comment by azovsky** [comment]
Oh! This can be closed.
