### ISSUE TITLE
Generic Request Handler -> Declaration must be compatible Error

### ISSUE THREAD

**Issue by Borsti26** [FreeDSx/LDAP#29]
Hello,

i want to create a generic request handler like discriped here:
https://github.com/FreeDSx/LDAP/blob/master/docs/Server/General-Usage.md#generic-request-handler

But i get the following error:
`PHP Fatal error:  Declaration of Foo\LdapRequestHandler::search(Foo\RequestContext $context, Foo\SearchRequest $search): Foo\Entries must be compatible with FreeDSx\Ldap\Server\RequestHandler\GenericRequestHandler::search(FreeDSx\Ldap\Server\RequestContext $context, FreeDSx\Ldap\Operation\Request\SearchRequest $search): FreeDSx\Ldap\Entry\Entries in /var/www/html/ldap.php on line 10`

Do you have any idea what i do wrong?

Thanks for help.

BR

**Comment by ChadSikorra** [comment]
Your $context and $search params need to properly resolve your type hints for the search method. Based off the exception, you need to add the proper use statements at the top of your PHP file.

**Comment by Borsti26** [comment]
Thanks
