### ISSUE TITLE
Start a LDAPS Server

### ISSUE THREAD

**Issue by trtracer** [FreeDSx/LDAP#30]
Hi, I want to run a LDAPS Server (on port 636) but how do I start it correctly? The "use_ssl" Option seems not to work. (StartTLS works, but that's not what I need). Is this really a missing feature?

I patched the constructor in ServerProtocolHandler.php and appended this:
```
if ($this->options['use_ssl'] === true) {
$this->queue->encrypt();
}
```
With this change, it works.

**Comment by ChadSikorra** [comment]
Using the server over 636 via SSL (commonly referred to as LDAPS), was never a feature I added. LDAPS was never a part of the official LDAP RFCs. The only method for encrypted LDAP documented in the protocol RFCs is via issuing a StartTLS command. I also do not have any use_ssl configuration documented for the server: 

https://github.com/FreeDSx/LDAP/blob/master/docs/Server/Configuration.md

That being said, I'm not really opposed to adding it as I support it on the client and it's a common thing for LDAP implementations to support (even though it was never standardized in RFC from).

**Comment by ChadSikorra** [comment]
Support for running the LDAP server in a SSL only made has been implemented in this commit: https://github.com/FreeDSx/LDAP/commit/aec139608c4fde2d5230c35cbbdf6dffd0e9df7f

I'll probably tag a new release sometime in the next week. Closing this out as the issue was opened quite some time ago.
