### ISSUE TITLE
Problem Creating account on OpenLDAP

### ISSUE THREAD

**Issue by TheBadalaMaster** [FreeDSx/LDAP#33]
I am using your library to create user accounts from Laravel to an OpenLDAP instance like this:

$uuid is auto incremented from the last user created uuid.

gidNumber is the user group I need the users to be a part of. Pass is a random string.

$nam is a username generated from the User given name. Problem is i can only create accounts with this structure:

cn=Test,cn=Users,ou=Groups,dc=test,dc=com
And i need to get this structure:

uid=Test,cn=Users,ou=Groups,dc=test,dc=com
When i change the first line after "new Entry(" from "cn" to "uid") it doesn't throw any error buy, it doesn't save the user on the directory.

I add the code i am using, thanks in advance.

```php
$pass = Str::random(10);
$ldap = new LdapClient([
    # Servers are tried in order until one connects
    'servers' => ['172.20.55.22'],
    # The base_dn is used as the default for searches
    'base_dn' => 'dc=test,dc=com'
]);
$ldap->bind('cn=admin,dc=test,dc=com', 'password');

$entry = (new Entry('cn=' . $nam . ',cn=Users,ou=Groups,dc=test,dc=co'))
   ->set('objectClass','top', 'inetOrgPerson', 'posixAccount', 'shadowAccount')
   ->set('uid', $nam)
   ->set('uidNumber', $uuid)
   ->set('gidNumber', $uuid)
   ->set('gidNumber', '2000')
   ->set('mail', $data['email'])
   ->set('userPassword', $pass)
   ->set('givenName', $first_name)
   ->set('sn', $last_name)
   ->set('loginShell', '/bin/bash')
   ->set('homeDirectory', '/home/' . $nam);


   try {
    $ldap->create($entry);
} catch (OperationException $e) {
    echo sprintf('Error adding entry (%s): %s', $e->getCode(), $e->getMessage()).PHP_EOL;
}
```

**Comment by ChadSikorra** [comment]
Hi @TheBadalaMaster . I have a feeling that the issue is with either OpenLDAP, or however you're checking / using the entry after creation rather than with this library. Given the above example, if you use the `uid` as the RDN in the DN, what does this return? Could add this after the `->create()` call to see if it can be found.

```php
$uid = 'replace-with-uid-of-user';

$entry = $ldap->read('uid=' . $uid. ',cn=Users,ou=Groups,dc=test,dc=co);

var_dump($entry);
```

**Comment by TheBadalaMaster** [comment]
Finally figured it out, missing "cn" as a separated parameter... But i was getting no error :D

**Comment by ChadSikorra** [comment]
Glad to hear you got it sorted out!
