### ISSUE TITLE
Proposal to change type hints to PhpDoc/Psalm/PhpStan/PhpStorm supported style

### ISSUE THREAD

**Issue by HenkPoley** [FreeDSx/LDAP#34]
I do have a lot of that prepared my local machine. But I haven't taken steps to cut it up into mergable chunks, since I'm not sure if the maintainer(s) can be swayed by '_well, this is how all PHP software reads & writes it_' 🤷‍♂️

It would be nice to not have all these tools complain about 'broken' things that are in fact, correct.

```
    /**
     * Create a logical 'and' filter, containing other filters.
     *
     * @param FilterInterface[] ...$filters  <---
     * @return AndFilter
     */
    public static function and(FilterInterface ...$filters): AndFilter
    {
        return new AndFilter(...$filters);
    }
```

Which every piece of software that I use interprets to mean "all inputs are FilterInterface arrays", to:

```
    /**
     * Create a logical 'and' filter, containing other filters.
     *
     * @param FilterInterface ...$filters  <---
     * @return AndFilter
     */
    public static function and(FilterInterface ...$filters): AndFilter
    {
        return new AndFilter(...$filters);
    }
```

Which means: "All inputs are a FilterInterface".

We could also just drop the typehint `@param` (and `@return`) in this case, since it's not any different from the actual type signature.

Can I get a 'We'll at least look at it'? Or would it be an immediate reject?

**Comment by ChadSikorra** [comment]
Hi @HenkPoley . I'd agree! Anywhere where a `@return` or `@param` type-hint exists but isn't different from the signature should just be removed, unless it contains some kind of comment that actually helps explain what its use is for. 

When I wrote this initially, the variadic support still wasn't the best in PhpStorm, and I probably messed up the phpdoc for it on accident. I'd welcome any changes that make the situation better.

**Comment by ChadSikorra** [comment]
Closing this out as the PR was merged.
