### ISSUE TITLE
Escaping strings, where?

### ISSUE THREAD

**Issue by HenkPoley** [FreeDSx/LDAP#36]
I see some escaping is being done inside FreeDSx/LDAP. But since you can't double this up without becoming compatible to other software, is there some escaping that still needs to be done on the library-consumer side?

I suppose when forming baseDN, you ought still use `'uid=' . ldap_escape($untrustedInputString, '', LDAP_ESCAPE_DN) . ,cn=example,cn=com` from the PHP ldap extension. This like equals sign ('=') or comma (',') in the untrusted input are probably pretty nasty in this case.

Any other places?

NB: ldap_unescape($str, $str2, LDAP_ESCAPE_DN) would be really nice too. Someone commented a PHP version a year ago: https://www.php.net/ldap_escape

**Comment by ChadSikorra** [comment]
If you're forming a LDAP filter using this library to be used somewhere else, then that should be escaped. But this library will escape all filters when output in string form, with the exception of using the `raw()` method to create a filter from a string. If you pass something to that...then it's up to you.

DNs are the only other exception. For that, if you have a user supplied value for a DN you could pass part of it through `FreeDSx\Ldap\Entry\Rdn::escape($value)`, which would perform the necessary escaping needed for use in a DN.

**Comment by ChadSikorra** [comment]
Let me know if you need any more details / clarification on it!  Closing this out for now.
