### ISSUE TITLE
How to fetch Manager

### ISSUE THREAD

**Issue by roylanceb** [FreeDSx/LDAP#39]
Hi,

How would I fetch the manager of a user? I have tried

`$search = Operations::search($filter, 'manager');`

But then

`$entry->get("manager")`

Returns nothing, even though I know the user has a manager

**Comment by ChadSikorra** [comment]
Are you using OpenLDAP or Active Directory? What does your filter look like? 

If you do `var_dump($entry->toArray());`, does it contain anything?

**Comment by roylanceb** [comment]
I've managed to get it working now. $entry->toArray() showed no manager field set. I went back and checked the user and their manager had actually been removed... sorry for the bother!

**Comment by ChadSikorra** [comment]
No worries, glad you got it sorted out!
