### ISSUE TITLE
Changing base_dn in setOptions() after bind() maybe ought to trigger an exception?

### ISSUE THREAD

**Issue by HenkPoley** [FreeDSx/LDAP#40]
Or, in a future API, bind() should return a different object that represents a bound connection ?

Currently at least someone was surprised that changing the base_dn after the fact didn't change anything 😂.

**Comment by ChadSikorra** [comment]
Yeah, I kind of regret making the options an array instead of an object with getters / setters. Which I feel is really the problem here. I could probably implement something like that (an options object), and deprecate the use of an options array at some point.

**Comment by ChadSikorra** [comment]
The original intention of the `base_dn` was supposed to be a one time default setting for client. Even if it could be changed after instantiating the client, it might lead to potentially confusing behavior / hard to find bugs, IMO. Might be better to explicitly set the different needed base_dn when building up the search operation.

**Comment by HenkPoley** [comment]
Personally I couldn't figure out how to make that work in the search operation. We have different OU (OU=something,DC=example,DC=com) for our groups and users. So I now just make 2 connections/binds/LdapClient.


btw, an Options object with getters and setters does not really represent the type of things that (may or) may not change.

**Comment by ChadSikorra** [comment]
> Personally I couldn't figure out how to make that work in the search operation. We have different OU (OU=something,DC=example,DC=com) for our groups and users. So I now just make 2 connections/binds/LdapClient.
> 
> btw, an Options object with getters and setters does not really represent the type of things that (may or) may not change.

Maybe it is more of a documentation issue, as I don't really specify anywhere what the method is. But the general way to do it would be:

```php
$operation = Operations::search($filter);
$operation->setBaseDn('ou=special,dc=foo,dc=bar');
```

Whether some options should change and at what point I feel are kind of up to the user of the library. Though I could take a more opinionated stance on it I guess. The current behavior is pretty unexpected. Though I think it's cleaner to probably have a factory that instantiates the client for different needs if you really need different sets of options for different uses.

**Comment by ChadSikorra** [comment]
I added the ability to force a disconnect when setting options on the client and added some notes in the docblock for it. At least this way you can force the client to get into a better state when changing certain settings. I think that's as much as I'll do on this one. Will be tagging a release sometime in the next month or so likely.

https://github.com/FreeDSx/LDAP/commit/cf0b5ac3b37ba0cc4ee42ddfca335d22cb531a8a
