### ISSUE TITLE
Support for connecting to server via unix socket

### ISSUE THREAD

**Issue by oucil** [FreeDSx/LDAP#45]
Please forgive me if this is already documented somewhere, I swear I've looked, and I've spent 30 min in the code and hadn't tracked an answer down ;)

I have a cloud server running a number of services, and I'm working to try to centralize their authentication in LDAP.  Because all services are on a single machine, I prefer to use unix sockets to connect if possible.  I was wondering if the `LdapClient` constructor supported the use of a unix socket reference instead of TCP?

Thanks!
Kevin.

**Comment by ChadSikorra** [comment]
Hi there @oucil. Currently communication over a Unix socket is not supported. I don't believe it's defined in any LDAP standard.

Though I could add support for it anyway. I'd need to first support it in the freedsx/socket library that this library uses for socket related communications.

**Comment by ChadSikorra** [comment]
I implemented support for this in PR https://github.com/FreeDSx/LDAP/pull/46. The integration test seems to work OK with it. I have not tested it myself though. Any chance you could test your code using the master branch in your environment to see if this will work for you? If it does I can tag a new release soon.

**Comment by oucil** [comment]
Wow @ChadSikorra!  First, sorry for not getting back sooner, on holidays with family, but I just saw your response and update, so thank you for getting back so quickly, and second, that's amazing that you've added support!  I'd be happy to pull down the master branch and give it a shot, though I'm off shortly for the next few days for new years, so it'll likely be after the 2nd, wish I could get to it sooner, very excited :)  

Thanks again, and have a happy new years!

**Comment by ChadSikorra** [comment]
> Wow @ChadSikorra! First, sorry for not getting back sooner, on holidays with family, but I just saw your response and update, so thank you for getting back so quickly, and second, that's amazing that you've added support! I'd be happy to pull down the master branch and give it a shot, though I'm off shortly for the next few days for new years, so it'll likely be after the 2nd, wish I could get to it sooner, very excited :)
> 
> Thanks again, and have a happy new years!

No worries, enjoy the holidays with the family! Whenever you get around to testing it is no problem. Often holidays and weekends are my only time to add to these personal projects I code lately. So my contributions to them are often at strange times. This gives me a little bit to add some more before tagging a new release.

**Comment by ChadSikorra** [comment]
This has been implemented and documented in the new tagged release. If you have any issues with it let me know and feel free to reopen this issue. Thanks!
