### ISSUE TITLE
How to use this library for authenticating a user

### ISSUE THREAD

**Issue by edwinmugendi** [FreeDSx/LDAP#55]
I'm working on a project that needs users to login using their already existing Active Directory accounts? 

Do you have sample code on how to use this library to login to Active Directory?

**Comment by ChadSikorra** [comment]
Hi @edwinmugendi 

To authenticate as a user in AD with this library you would do something like shown in the first part of the "Getting Started" section of the readme:

```php
use FreeDSx\Ldap\LdapClient;

$ldap = new LdapClient([
    'servers' => [
        // Can use the name of your AD domain here...
        'my-ad-domain-name.local',
    ],
]);

# Encrypt the connection prior to authentication...
$ldap->startTls();

# Authenticate to LDAP with a specific AD user.
# This will throw a BindException if it fails.
$ldap->bind(
    'username@my-ad-domain-name.local,
    '12345'
);
```

**Comment by edwinmugendi** [comment]
Thanks Chad for your advise. 

I'll try it out. 

I develop on linux and I've never worked with AD. 

Are there free accessible AD test beds or environment that I can find online for development so that I don't have to install Windows Server and continue development from Linux?

**Comment by ChadSikorra** [comment]
If you're doing this from linux and the server the library is running on isn't joined to the domain, you may have to adjust client options a little:

 ```php
$ldap = new LdapClient([
    'servers' => [
        // May have to replace this with the domain controller IP address
        'my-ad-domain-name.local',
    ],
     // If you can get a copy of the AD SSL public CA cert on the linux machine, reference the path here so startTls() works.
    'ssl_ca_cert' => '/path/to/cert.crt',
    // If you cannot get a copy of the cert above, as a last resort you could disable cert checking
    'ssl_validate_cert' => false,
]);
```

But it all depends on how the server is configured.

Regarding an accessible AD test bed, I'm not familiar with any myself that are exposed on the internet. You could perhaps use free Azure credits to spin-up a small AD server in a VM in Azure and test it there (though that assumes you have some Azure background to do that).  You could also register for a trial version of Windows Server and setup AD in Virtualbox or something: https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server-2019 . That's also a bit of effort too unfortunately.

**Comment by edwinmugendi** [comment]
Thanks again Chad for your quick response and helpful information. 

I'll check and revert. 

I've found a test server on this link: 

https://www.forumsys.com/2022/05/10/online-ldap-test-server/
