### ISSUE TITLE
Required OS

### ISSUE THREAD

**Issue by getSwiftly** [FreeDSx/LDAP#6]
Hello, can anyone guide me I need to get this LDAP server up and running on a vm or dedicated server. What OS is required for the setup of the server? I understand the basic code and everything but the code on the server is giving me some error as given below: 

> Fatal error: Uncaught FreeDSx\Ldap\Exception\RuntimeException: The PCNTL extension is needed to fork incoming requests, which is only available on Linux. in /opt/lampp/htdocs/ldap-api-php/vendor/freedsx/ldap/src/FreeDSx/Ldap/Server/ServerRunner/PcntlServerRunner.php:40 Stack trace: #0 /opt/lampp/htdocs/ldap-api-php/vendor/freedsx/ldap/src/FreeDSx/Ldap/LdapServer.php(54): FreeDSx\Ldap\Server\ServerRunner\PcntlServerRunner->__construct(Array) #1 /opt/lampp/htdocs/ldap-api-php/index.php(48): FreeDSx\Ldap\LdapServer->__construct() #2 {main} thrown in /opt/lampp/htdocs/ldap-api-php/vendor/freedsx/ldap/src/FreeDSx/Ldap/Server/ServerRunner/PcntlServerRunner.php on line 40

**Comment by ChadSikorra** [comment]
The server component requires the [PCNTL](http://php.net/manual/en/book.pcntl.php) extension. Perhaps PHP was not compiled with PCNTL enabled on your server? Or perhaps it was disabled in your PHP INI. If it's not loaded this would return nothing:

```sh
php -m | grep pcntl
```

**Comment by getSwiftly** [comment]
you are right it did return nothing. How to enable the extension, it would be via the PHP INI only or there is any other possibility?

**Comment by ChadSikorra** [comment]
What Linux distro are you using? Are you on a shared hosting server, or is this your own server that you have full access to? What does the following return?

```sh
php --ri pcntl
```

The way to enable it is going to vary depending on your setup. You could re-compile PHP (if you built from source) with `--enable-pcntl` specified. Or you could compile just the extension and then reference the built extension in your PHP.INI with ` extension=pcntl`.

**Comment by getSwiftly** [comment]
I simply installed apache server on MacOS and on CentOS 7. Both returned the same response. PHP was never compiled explicitly. So I guess I would have to download php package 7.0 version or higher right?
Then enable pcntl and try again.

**Comment by ChadSikorra** [comment]
It appears like pcntl is only on the php-cli package in CentOS. This post
has some helpful suggestions:

https://serverfault.com/questions/158113/installing-pcntl-module-for-php-without-recompiling

As far as Mac and the PCNTL module goes, I'm not sure about that one.

**Comment by getSwiftly** [comment]
What about compatibility with a demain server OS distribution?

**Comment by getSwiftly** [comment]
Getting this: 

> Parse error: syntax error, unexpected '?' in /var/www/html/ldap-api-php/vendor/freedsx/ldap/src/FreeDSx/Ldap/Tcp/SocketServer.php on line 85

The same occurs at line 54: syntax error, unexpected '?' in LdapServer.php.

After fixing the pctnl issue. Any help?
Using Ubuntu 16.04 and PHP 7.0

**Comment by plewin** [comment]
Hi @getSwiftly 

You need at least php 7.1
https://github.com/FreeDSx/LDAP/blob/master/composer.json#L16

**Comment by ChadSikorra** [comment]
Yep, at least PHP 7.1 is required. I typically use this PPA for the most recent PHP builds on Ubuntu:

https://launchpad.net/~ondrej/+archive/ubuntu/php

**Comment by getSwiftly** [comment]
Thank you, I got it working a few days back. Can you tell me how to serve gpg --keyserver ldap://my-keyserver-IP --search-keys random@email.com requests cz those I cannot parse from the SearchRequest object.

**Comment by ChadSikorra** [comment]
I'm not familiar with that sort of request unfortunately. I assume it's to be used for some sort of authentication?

**Comment by getSwiftly** [comment]
This is a mechanism that anyone can do to fetch key from an ldap server. This makes other servers search for keys on your ldap server. The search request object does get received from gpg command but the filters and attributes come as protected rather than plain text. I was able to parse search filters when getting request from your code's client and other LDAP clients but not via GPG.

**Comment by ChadSikorra** [comment]
If you're talking about parsing the search request it's sending to the LdapServer component, you can get the filter by doing `$search->getFilter()->toString();`. That will transform it to normal string LDAP filter. Depending on what information you need you can parse out the filters with the individual methods (like `getValue()` for the equality type of filters, etc. Or is it throwing an error before you can even try to parse the search request object?

**Comment by getSwiftly** [comment]
I have done and was able to parse the filters when request comes from a client based app. When a gpg command the parameters show up as protected or like this: "string(15) "(objectClass=*)"". The filter don't get decrypted. Does this have to do with the fact that Im running just LDAP not LDAPS?

**Comment by getSwiftly** [comment]
This is what I get when I run the command:
Command line command: 
> gpg --keyserver ldap://localhost --keyserver-options "binddn=\"uid=user\"" --keyserver-options bindpw=12345 --keyserver-options verbose --search-keys somemail

Response: 

> object(FreeDSx\Ldap\Operation\Request\SearchRequest)#41 (8) {
  ["baseDn":protected]=>
  object(FreeDSx\Ldap\Entry\Dn)#42 (2) {
    ["dn":protected]=>
    string(36) "cn=pgpServerInfo,dc=FreeDSx,dc=local"
    ["pieces":protected]=>
    NULL
  }
  ["scope":protected]=>
  int(0)
  ["derefAliases":protected]=>
  int(0)
  ["sizeLimit":protected]=>
  int(0)
  ["timeLimit":protected]=>
  int(0)
  ["attributesOnly":protected]=>
  bool(false)
  ["filter":protected]=>
  object(FreeDSx\Ldap\Search\Filter\PresentFilter)#15 (1) {
    ["attribute":protected]=>
    string(11) "objectClass"
  }
  ["attributes":protected]=>
  array(3) {
    [0]=>
    object(FreeDSx\Ldap\Entry\Attribute)#38 (3) {
      ["attribute":protected]=>
      string(17) "pgpBaseKeySpaceDN"
      ["lcAttribute":protected]=>
      NULL
      ["values":protected]=>
      array(0) {
      }
    }
    [1]=>
    object(FreeDSx\Ldap\Entry\Attribute)#39 (3) {
      ["attribute":protected]=>
      string(10) "pgpVersion"
      ["lcAttribute":protected]=>
      NULL
      ["values":protected]=>
      array(0) {
      }
    }
    [2]=>
    object(FreeDSx\Ldap\Entry\Attribute)#40 (3) {
      ["attribute":protected]=>
      string(11) "pgpSoftware"
      ["lcAttribute":protected]=>
      NULL
      ["values":protected]=>
      array(0) {
      }
    }
  }
}

**Comment by ChadSikorra** [comment]
Yes, so it is running a search request against the server which translates to this object:

https://github.com/FreeDSx/LDAP/blob/master/src/FreeDSx/Ldap/Operation/Request/SearchRequest.php

See the public methods there to see how to decipher the request.

Based on that object dump, it's searching any object (filter `objectClass=*`) at the baseDn level `cn=pgpServerInfo,dc=FreeDSx,dc=local` and asking for the attributes of  `pgpVersion` and `pgpSoftware` from them. The LDAP server component has no persistence layer, so it is then your responsibility to respond back with entries containing the `pgpVersion` and `pgpSoftware` attribute values back to the client.

**Comment by getSwiftly** [comment]
But the string given for search is my email and I cannot find it in the filters. In other client requests I was able to parse filters using string and parsing it but here I guess there is no way to parse and find the email string?

**Comment by ChadSikorra** [comment]
Above this line:
https://github.com/FreeDSx/LDAP/blob/d8a4ed4d21eacbf5510a51e3529c00cf377446ca/src/FreeDSx/Ldap/Operation/Request/SearchRequest.php#L389

Add:

`var_dump($type->getChild(6));`

It's possible I'm not parsing the ASN.1 for the filter properly. If that's the case, then you would see the email in that var_dump output somewhere.

**Comment by getSwiftly** [comment]
No use, this is what that link dumped:

`05c0

?
 objectClass0namingContextsobject(FreeDSx\Ldap\Asn1\Type\IncompleteType)#21 (4) {
  ["value":protected]=>
  string(11) "objectClass"
  ["tagNumber":protected]=>
  int(7)
  ["taggingClass":protected]=>
  int(128)
  ["trailingData":protected]=>
  NULL
}
0ucp$cn=pgpServerInfo,dc=FreeDSx,dc=local

?
 objectClass0,pgpBaseKeySpaceDN
pgpVersion`

**Comment by ChadSikorra** [comment]
Based on that, It really doen't appear like it's sending the email in the request (in the filter anyway). One way to completely rule it out would be to do a wireshark capture / tcpdump and inspect the packets to see what it's actually sending across the wire.

**Comment by getSwiftly** [comment]
In short your ldap server will not be able to parse or serve gpg requests cz its a different thing?

**Comment by getSwiftly** [comment]
Do you know what format I can send the public key and email and other details of a user's key back to the requesting body?
In form of entries array?

**Comment by ChadSikorra** [comment]
Cleaning up some old issues here. After re-reading this, it appears that this is very GPG specific. This instructions detail the setup:

https://gnupg.org/blog/20201018-gnupg-and-ldap.html

It has its own OpenLDAP specific schema needed, and then the gpg tools interact with it. Unfortunately this is outside the scope of this project.
