### ISSUE TITLE
Can it work with PHP 7.0?

### ISSUE THREAD

**Issue by cymapgt** [FreeDSx/LDAP#9]
It seems you are only supporting PHP 7.1 and above. Is it a technology issue which limits supporting 7.0?

**Comment by ChadSikorra** [comment]
There's no technical reason why it couldn't work with PHP 7.0. That said, there's probably no technical reason it couldn't work PHP 5.3 or lower either. However, I ultimately decided on PHP 7.1 as it was the latest stable release at the time I started the library. And nullables are also extremely handy when utilizing primitive type hinting.

So unfortunately I do not plan any releases that support lower PHP versions.

**Comment by cymapgt** [comment]
Thanks for confirming that it is not technical issue. Needed it for a project that support minimum 7.0
